#include<iostream>
#include<string>
#include <Windows.h>
#include"getCorrectValues.cpp"

using namespace std;


void StoryBeforeLevel(int level, int character) {
	if (level == 1 && character == 1)
	{
		cout << "Sheila's spacecraft signaled a high intelligence species on a strange planet so she "<< endl;
		cout <<"decided to land there with the intention of finding a scientist capable of building her a robotic."<< endl;
		cout <<"head. She found out after the landing that the name of the planet was X ' A-Xii and the  "<< endl;
		cout <<"planet was ruled by a primal descendent of earth's gorilas. Maximam Sapiens( the intelligent "<< endl;
		cout <<"species) were being overpowered by the gorillas and begged her for help. She infiltrated the  "<< endl;
		cout <<"gorilas base and started fighting the King Shitta."<< endl;
		cout <<"Sheila: 'Those poor Maximam Sapiens don't deserve being opressed by dumb and primal "<< endl;
		cout <<"animals like you! Hope your death makes every gorilla see you should stop killing them! "<< endl;
		cout <<"Prepare yourself to die."<< endl;
		cout <<"King Shitta : 'WUGA WUGA!ARRRGHHH" << endl;
		cout<<"                          i@dg                                     "<<endl;
		cout<<"                       g0gggggkx                                   "<<endl;
		cout<<"                      g@ggggg@@@g.                                 "<<endl;
		cout<<"                    gg@@@@@gggg@@@                                 "<<endl;
		cout<<"                   gg@gggggg@gg@g@g                                "<<endl;
		cout<<"                  y@ggggggggggggg@@                                "<<endl;
		cout<<"                  @ggggggahggggg@@@@                               "<<endl;
		cout<<"                 f0000w000000ggg@@00g                              "<<endl;
		cout<<"                 F0@g0ggg,ggggggg@0m@g'                            "<<endl;
		cout<<"                -g10g000 * 0ggggg@@g@@g                            "<<endl;
		cout<<"                ggg!b000g/g0gggggg@@@@@@0                          "<<endl;
		cout<<"               u@gp0mq0#00ggggggg@@@gg@@g                          "<<endl;
		cout<<"                @gdg00g0gggggggg@@@gg@@@@@                         "<<endl;
		cout<<"               m@#000000000ggggg@@gggggggg@q                       "<<endl;
		cout<<"              gggq00b000000g#gg@@@gggggggg@@h                      "<<endl;
		cout<<"              mgg000p00000g00g@@ggggggggggg@@                      "<<endl;
		cout<<"              ggggggggggg#000g@gggggggggggg@@                      "<<endl;
		cout<<"              ggggggknF00000ggggggggggggggg@@@                     "<<endl;
		cout<<"              gggggg000000ggggggggggggggggg@@@g@T                  "<<endl;
		cout<<"              ggggg@ggggggggg00gggggggggggg@@@ggggggg@d            "<<endl;
		cout<<"              ggggg@00000000000gggggggggggg@@ggggggggggg#          "<<endl;
		cout<<"              gggggm0000000m000ggggggggggg@@@gggggggggggg@         "<<endl;
		cout<<"              gggggg0000000g000ggggggggggg@@@ggggggggggggg#        "<<endl;
		cout<<"              gggggg00000000#00gggggggggg@@@00000mgggggggg@'       "<<endl;
		cout<<"            :gggggggg000000#ggggggggggggg@@00000000ggggggg@g       "<<endl;
		cout<<"            ggggggggg@#00#ggg00gggggggg@@@g00000#g@ggggggg@@       "<<endl;
		cout<<"           -ggggggggg@@'000000ggggggggg@@@gggggggggggggggg@@       "<<endl;
		cout<<"           gggggggggg@@'-g000ggggggggg@@@@gggggggggggggggg@g       "<<endl;
		cout<<"           !gggggggg@@@   _gggggggggggg@@@ggggggggggggggg@@+       "<<endl;
		cout<<"           mgggggggg@@@      ggggggggg@@@gggggggggggggggg@@        "<<endl;
		cout<<"           ggggggggg@@#     mgggggggggg@@ggggggggggggggg@@0        "<<endl;
		cout<<"            gggggggg@@      _ggggggggg@@ggggggggggggggggg@g        "<<endl;
		cout<<"            -gggggg@@,       gggggggg@@@ggggggge; gggggggg@g       "<<endl;
		cout<<"             gggggg@@       -gggggggg@@gggg@@     ggggggggg@g      "<<endl;
		cout<<"             tggggg@1       .gggggg@@@ggggg@=      ggggggggg@'     "<<endl;
		cout<<"              ggggg@`        ggggg@@ _gggggg@      jgggggggg@g     "<<endl;
		cout<<"              agggg@-        ggggg@@  @gggg@@r      gggggggg@@     "<<endl;
		cout<<"               ggg@@e        gggg@@   g@g@@@@v'      ggggggg@-     "<<endl;
		cout<<"              ,g@@@@mh       @@@@@@.#00@g@@g@@@       gggggg@      "<<endl;
		cout<<"               #@#@00g       @@gggg_#00g#0000g0       @@g@@@g      "<<endl;
		cout<<"              !00000gg       d00#0g   ggmv_,.       000mm@0gg`     "<<endl;
		cout<<"              m000#00g      .00000gg              0#m00000mgT      "<<endl;
		cout<<"               | g5gk       Dmgggmgg               ng#g#|          "<<endl;

	}
	else if (level == 1 && character == 2)
	{
		cout << "Stuart was travelling around the space with his spaceship when he found a particular "<< endl;
        cout <<"planet. This planet had rings around it and besides the absence of atmosphere there was life"<< endl;
        cout <<"there. As the curious guy he always is, Stuart decided to land there looking for some "<< endl;
        cout <<"answers to feed his questions about that planet and its origin."<< endl;
        cout <<"As he arrived on the surface, a group of creatures came to his way. Despite the fact Stuart"<< endl;
        cout <<"didn't understand them, they were really nice. It looked like no one ever landed there so the"<< endl;
        cout <<"creatures were also surprised how Stuart looked."<< endl;
        cout <<"Soon Stuart realised there was a hierarchy there and that not everyone had access to the"<< endl;
        cout <<"basic necessities. Stuart had seen some similar situation before, but this time he was "<< endl;
        cout <<"wheeling to fight and help those creatures with so pure hearts."<< endl;
        cout <<"The only way to end that situation was to kill the president so Stuart planned how to get to"<< endl;
        cout <<"him without getting attention from other people."<< endl;
        cout <<"On a certain day, after 10 planning days, Stuart head up to the president's secret location.To "<< endl;
        cout <<"do that, Stuart had the help of some creatures that he met. Those creatures were probably"<< endl;
        cout <<"the truest friend he ever had."<< endl;
        cout <<"When he got there he confronted the president:"<< endl;
        cout <<"-'You should be ashamed for ruling this place like this. Your people deserve so much more. "<< endl;
        cout <<"They deserve some good to rule them. I know that you are the official president but you don't "<< endl;
        cout <<"deserve that and according to the rules here, the only way to get rid of you is killing you.'- "<< endl;
        cout <<"Stuart stayed in the local idiom."<< endl;
        cout <<"-'And is it you that are going to kill me? Ahah good luck with that' - The President replied "<< endl;
        cout <<"seconds before the fight begin."<< endl;
		cout<<"                                                                                  "<<endl; 
		cout<<"                                                                                  "<<endl;
		cout<<"                                                 -kfOO#                           "<<endl;
		cout<<"                                               i=FEIdI*dg@i                       "<<endl;
		cout<<"                                             ´noel@bxTria#@g!                     "<<endl;
		cout<<"                                             gmmpk!*::y!c#@!z|                    "<<endl;
		cout<<"                                            @g@gj__;,:nFtOOw@g!g-                 "<<endl;
		cout<<"                                          -@ggggo_:~ _ggg=g#gggT@x  -- -          "<<endl;
		cout<<"                                          ndh@@gm_!;_ug##rg@@g@@ eI__m@           "<<endl;
		cout<<"                                         ggggggggmse6gg@@@ggd#ma!F#gg#a/,         "<<endl;
		cout<<"                                       ´e@g@ggggmObgf@@ggggg@g@i@qggFpog,         "<<endl;
		cout<<"                                       wg;# _@ggggmgggg@@@@@@gggggsm@gggg         "<<endl;
		cout<<"                                       ng,#Tg@g@ggg@@g@@@@@@g@gg@@@@@migb         "<<endl;
		cout<<"                                       pg`Odgg!biowg@@@m@@I@gg@gggg@ggggg         "<<endl;
		cout<<"                                       b@ Og@g@@@x/s@@g@g@m@@g@@@@ggggqgg         "<<endl;
		cout<<"                                       Og`xUgggg@ieegggg\e@@gge#O@Uwggggg-        "<<endl;
		cout<<"                                       ~~gkw@g#@O@@@gItohd@ggUgObx~Oggggug        "<<endl;
		cout<<"                                       !i@ggggfTggbbggggOq@@gmUpsOg~@gggge        "<<endl;
		cout<<"                                       x;gg@q!#ngg@y@ggUgUgggqdfggg@@gmg~         "<<endl;
		cout<<"                                       g/zUgU++1Ug@nbbggwh@g@@g|@@gg@@g~          "<<endl;
		cout<<"                                       #1tcgmggggggggggggqeg@@@@gggg@gg           "<<endl;
		cout<<"                                   `  E/!dnseggUgmd@bg#UggoUg@@@agug#d@n          "<<endl;
		cout<<"                               -ggygg@ei#F+b.UggmgggmggggUIyggqO~n@ggO@g          "<<endl;
		cout<<"                           ~OOmegkbwOggg´!F   g1uUiggqum1pEqU#gg_gggpgga          "<<endl;
		cout<<"                        vOnFOu@#qgg@@g.        g*ggzIgOggmdEmtOgkFggmUgU@         "<<endl;
		cout<<"                     `'1 ggggggggg@@r          glggEIggg@@g#IvO   d1gg@O          "<<endl;
		cout<<"                 ;-'' qd1yuggghqpc           kg@@gggghggxmg@g# @E  'g@@g1         "<<endl;
		cout<<"               :   ,;I-gEumd                #gggegqOg@gEpgggg#@@   .gggq         "<<endl;
		cout<<"                ´|     @g_                   _gggggmgmEgg@ggggh@@v  .gg@dqT       "<<endl;
		cout<<"              ´;.                           .tbggggggTTgggngggkg    gg@@ggO       "<<endl;
		cout<<"            . !                             @qh@gggUpbqggUs_ggb+    gg@g1gb       "<<endl;
		cout<<"            -/                            ;@#gggggpggagggOfIgmOq    g#@mtgk       "<<endl;
		cout<<"            ;                            ;@tgg!#UgggkOgg#ggggg@f,   gggdg@#       "<<endl;
		cout<<"                                        dggOO=#ggghgygggi|~;g*o_n   gggOwTo       "<<endl;
		cout<<"                                        #f>;;hgOs!VVgg@o!x1;,;!T!   ggggo#`       "<<endl;
		cout<<"                                        `,~g+m_ggmqgg#bglmox!~_!!   ggm@@@        "<<endl;
		cout<<"                                  g`   _eyE!;Ts|dggggjgg~Off~qe_=T -g@@gg´!       "<<endl;
		cout<<"                                  g   zte;`!xgghggggggg `OFF::T1g gdggg!         "<<endl;
		cout<<"                                 -U.  gz_k_!gTxwggdmOEI -Qmm;q;ymgOgqggg,         "<<endl;
		cout<<"                                 hg-#ggr!Tktgggg-         Ocxgg#magU1g@g.         "<<endl;
		cout<<"                                 b@./xgbOn/rbg             Odggg!;x`-gv           "<<endl;
		cout<<"                                ,@@x_yUaOg1bd.              Oo_u,O;a!             "<<endl;
		cout<<"                               jj'!vyfmOOq-                `g|--;!gg.             "<<endl;
		cout<<"                                phcphF#j'                     Or!Ilggq            "<<endl;
		cout<<"                                ggpFagnIx                     oohevgggx           "<<endl;
		cout<<"                                gdgg#hgg#                      ypeOEd#g           "<<endl;
		cout<<"                               'm##dI#m#O                     .qbOpmgOgn          "<<endl;
		cout<<"                               ,gwOOeOF#                      Tbophgggg          "<<endl;
		cout<<"                                gpgggded                        pqgOEFg#          "<<endl;
		cout<<"                               o@oggO#O                          wUmOmgm          "<<endl;
		cout<<"                                ,igwsp,                            nupUg'         "<<endl;
		cout<<"                                ggaOg,                            xOO#gg'        "<<endl;
		cout<<"                                -gggbU=                             mOOggd        "<<endl;
		cout<<"                                gg@gOe-                             bgg#Uh        "<<endl;
		cout<<"                            .Fg#ggwg@_                              s@ggggxgg.    "<<endl;
		cout<<"                          .gggggh7=ggg                              Tguggggg-gg.  "<<endl;
		cout<<"                          a@g@gUhggmg                               Eg!gpppgggE.  "<<endl;
	}
	else if (level == 1 && character == 3)
	{
		cout << "Azreal was flying in space, full of rage and despite of his father. He was searching for "<< endl;
		cout <<"some way to earn his powers back in order to get revenge on his father later. He got curious"<< endl;
		cout <<"when he saw a planet similar to earth (Last time he was on earth he run on some problems"<< endl;
		cout <<"but that is all other story') with this curiosity he decided to land on that planet and "<< endl;
		cout <<"investigate the life form that lived there."<< endl;
		cout <<"After he landed a group of giant gorillas confronted him. It looked like they have"<< endl;
		cout <<"never seen someone as powerful as him even without his full power Azreal had a "<< endl;
		cout <<"threatening presence. The gorillas didn't have the ability to speak, so Azreal tried to befriend"<< endl;
		cout <<"them by just being next to them and learning their culture. When the night time arrived the"<< endl;
		cout <<"gorilas started to get aggressive. Seemed like the species was affected by the dark in some"<< endl;
		cout <<"way. They all  attacked Azreal, but not with the intention of killing him so Azreal didn't even "<< endl;
		cout <<"bother to fight back. The gorilas brought him to the Arena. The arena was very primal, a"<< endl;
		cout <<"circle made out of some big wood logs and leaves. After a while a gorilla bigger than the"<< endl;
		cout <<"others jumped into the arena and made some war noises. Azreal got the message if he"<< endl;
		cout <<"wanted to prove himself to them he needed to win the fight'"<< endl;
		cout <<"Gorila: 'WOO WOO ARGHH'"<< endl;
		cout <<"Azreal: 'So it shall be. Let's do this!'"<< endl;
		cout<<"                          i@dg                                     "<<endl;
		cout<<"                       g0gggggkx                                   "<<endl;
		cout<<"                      g@ggggg@@@g.                                 "<<endl;
		cout<<"                    gg@@@@@gggg@@@                                 "<<endl;
		cout<<"                   gg@gggggg@gg@g@g                                "<<endl;
		cout<<"                  y@ggggggggggggg@@                                "<<endl;
		cout<<"                  @ggggggahggggg@@@@                               "<<endl;
		cout<<"                 f0000w000000ggg@@00g                              "<<endl;
		cout<<"                 F0@g0ggg,ggggggg@0m@g'                            "<<endl;
		cout<<"                -g10g000 * 0ggggg@@g@@g                            "<<endl;
		cout<<"                ggg!b000g/g0gggggg@@@@@@0                          "<<endl;
		cout<<"               u@gp0mq0#00ggggggg@@@gg@@g                          "<<endl;
		cout<<"                @gdg00g0gggggggg@@@gg@@@@@                         "<<endl;
		cout<<"               m@#000000000ggggg@@gggggggg@q                       "<<endl;
		cout<<"              gggq00b000000g#gg@@@gggggggg@@h                      "<<endl;
		cout<<"              mgg000p00000g00g@@ggggggggggg@@                      "<<endl;
		cout<<"              ggggggggggg#000g@gggggggggggg@@                      "<<endl;
		cout<<"              ggggggknF00000ggggggggggggggg@@@                     "<<endl;
		cout<<"              gggggg000000ggggggggggggggggg@@@g@T                  "<<endl;
		cout<<"              ggggg@ggggggggg00gggggggggggg@@@ggggggg@d            "<<endl;
		cout<<"              ggggg@00000000000gggggggggggg@@ggggggggggg#          "<<endl;
		cout<<"              gggggm0000000m000ggggggggggg@@@gggggggggggg@         "<<endl;
		cout<<"              gggggg0000000g000ggggggggggg@@@ggggggggggggg#        "<<endl;
		cout<<"              gggggg00000000#00gggggggggg@@@00000mgggggggg@'       "<<endl;
		cout<<"            :gggggggg000000#ggggggggggggg@@00000000ggggggg@g       "<<endl;
		cout<<"            ggggggggg@#00#ggg00gggggggg@@@g00000#g@ggggggg@@       "<<endl;
		cout<<"           -ggggggggg@@'000000ggggggggg@@@gggggggggggggggg@@       "<<endl;
		cout<<"           gggggggggg@@'-g000ggggggggg@@@@gggggggggggggggg@g       "<<endl;
		cout<<"           !gggggggg@@@   _gggggggggggg@@@ggggggggggggggg@@+       "<<endl;
		cout<<"           mgggggggg@@@      ggggggggg@@@gggggggggggggggg@@        "<<endl;
		cout<<"           ggggggggg@@#     mgggggggggg@@ggggggggggggggg@@0        "<<endl;
		cout<<"            gggggggg@@      _ggggggggg@@ggggggggggggggggg@g        "<<endl;
		cout<<"            -gggggg@@,       gggggggg@@@ggggggge; gggggggg@g       "<<endl;
		cout<<"             gggggg@@       -gggggggg@@gggg@@     ggggggggg@g      "<<endl;
		cout<<"             tggggg@1       .gggggg@@@ggggg@=      ggggggggg@'     "<<endl;
		cout<<"              ggggg@`        ggggg@@ _gggggg@      jgggggggg@g     "<<endl;
		cout<<"              agggg@-        ggggg@@  @gggg@@r      gggggggg@@     "<<endl;
		cout<<"               ggg@@e        gggg@@   g@g@@@@v'      ggggggg@-     "<<endl;
		cout<<"              ,g@@@@mh       @@@@@@.#00@g@@g@@@       gggggg@      "<<endl;
		cout<<"               #@#@00g       @@gggg_#00g#0000g0       @@g@@@g      "<<endl;
		cout<<"              !00000gg       d00#0g   ggmv_,.       000mm@0gg`     "<<endl;
		cout<<"              m000#00g      .00000gg              0#m00000mgT      "<<endl;
		cout<<"               | g5gk       Dmgggmgg               ng#g#|          "<<endl;

	}
	else if (level == 2 && character == 1)
	{
		cout << "Sheila did some research on the ancient guardian of science and found out that in order to  "<< endl;
		cout <<"summon him you need to defeat a beast. This beast is called Cerberus, the guardian of the "<< endl;
		cout <<"gates of the godlyhood."<< endl;
		cout <<"When she arrived at the gates she encountered the beast right on. Cerberus was "<< endl;
		cout <<"1 km tall and had three furious dog heads. "<< endl;
		cout <<"Sheila: ' Seems like you shall be a good test to my new sword.'"<< endl;
		cout <<"Cerberus: 'RRRRGHHH AAAAUUUU'."<< endl;
		cout <<"                                                                              "<<endl;                                       
		cout <<"                        -@g                                                   "<<endl;
		cout <<"                  g    ,@U@                        :@                         "<<endl;
		cout <<"                  -O@   ggpg               @       ag#        pg@g@           "<<endl;
		cout <<"                   ggg@@@g#@b     g@      @gb      OUI@@@ggg@@@@@#@@          "<<endl;
		cout <<"                  g@gggg@@g@gg@   gO@    @@#w      @g@O@gg@g@@@@@@@@          "<<endl;
		cout <<"                @@@@@U@@g@@@@@@@n @O@@@q#O@gg      @@@m@@@@@@@@@@@g@          "<<endl;
		cout <<"                @ggg@@@ggggg@gg@@O@gg@g@@g@@g     g#gg@@@@@@@@@@@@p!          "<<endl;
		cout <<"              @mggggg@@@@gU@@@@@g@hg@@@g@@@@gh   ggOg@@@@@@@@@g!1@v@          "<<endl;
		cout <<"              O@@@@@g@@@@@@@@@@@ggo@@@@g@@@@@y@ @@@@gg@@@@@@az~@g@@@          "<<endl;
		cout <<"              g@@@@@@@@v1*E@@@@@g@g@@@@#@@@@@gg@oggggg@@@@@@@gq@@@g           "<<endl;
		cout <<"              @@´100qg=xiv@@@@@@O@@@@@@@@@@@@g@ggggg@@@@@@@g@@@=             "<<endl;
		cout <<"              ~@=+t !@p@g_@g@@@@@m@@@@@@wan@@@@g@@gg@@@@@@@@@@@~              "<<endl;
		cout <<"         O       /@!gI.ggg@g@@@@@@@ggTgEey!@@@@@@@@@@@@@@@@@@#`               "<<endl;
		cout <<"        g         @gg@@@@@@@@@@@@xg=_@. rOp:@@@g@@@@@@@@@@@-                 "<<endl;
		cout <<"       g          EU@@@@@@@@@@@@@@ifgZg@bgct#@#@@@@@@@@@@@@@                  "<<endl;
		cout <<"      g@           -gg@g@@@@@@@@@gk@@gqpgqhq@@@g@@@@@@@@@@@@                  "<<endl;
		cout <<"      U@             =@f#@@@@@@@@@m_@;ggaq@rg~@@@@@@@@@@@@@@                  "<<endl;
		cout <<"      g@            @|@g#@@@@@@@@g@g@znUdb,;@@@@@@g@@@@@@@@@                  "<<endl;
		cout <<"      g@g         -@@g@@n@@@@@@g@@b@;.ggeg@g@@@@@@FggOOm@g@d                  "<<endl;
		cout <<"       g@@       g@g@@j@@@@@@@@@@@g@g@@g@@@@@@@@@g@@@gg@@b@gr                 "<<endl;
		cout <<"       g@@@g   @cgh@@ggy@gm@gO#O#g@@@@g@@g@@@@@@@@@@@@@@@@-                   "<<endl;
		cout <<"        #@@g@@g@@@@gggg@g@O@@@@@@@@@@gg@@@@@@@vg*#@@@@@@@@                    "<<endl;
		cout <<"         @@pg@@@gmggggg@@@g@@@@@@@@@@#g@g@gggg@@@@@@@@@@@                     "<<endl;
		cout <<"         h@gggg@@O@ggggg@@@g@@@@@@@@@g@@g@gUUggg@@@@@@@g@                     "<<endl;
		cout <<"         F@g@g@@@@@@ggg@@@@@@@@@@@@@@U@@@@@@@@@@@@@@@@@@g                     "<<endl;
		cout <<"         @@@gg@@@m@@gg@@@@@@@@@@@@@@@g@@@@@@@@@@@@@@@g@gg@                    "<<endl;
		cout <<"        vO@ggg@@@q@gg@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@gg@i                   "<<endl;
		cout <<"        @g@@gg@@@k@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ggggm                   "<<endl;
		cout <<"        @@g@@@@@@u@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@g@@@@@@@@g                   "<<endl;
		cout <<"        @@@@@@@@g@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@g@@@@@@@@g@@                   "<<endl;
		cout <<"        @@g@@@@@m@@@@@@@@@g@@@@@@@@@@@@@@@@@@g@@g@@@@@@@@gg1                  "<<endl;
		cout <<"        @@@@@@@g@@@@@@@@@@@@@@@@@@g@@@@@@@@@@@@g@@@@@@@@@@@E                  "<<endl;
		cout <<"       g@@@@@@@@@@@@g@@@@@@@@@@@@g@@@@@@@@@@@@e zb@@@@@@@@@c                  "<<endl;
		cout <<"      b#@@@@gg @@g@@@@@@j  .@@@@@@@              @@@@@@@@@@                   "<<endl;
		cout <<"      @@@@@gg   @@@@@@@@@  @E@@@@@                @@@@@@@@gy                  "<<endl;
		cout <<"      g@@@g:    r@@@@@@@@  m@@@@@                  @@@@@@@I                   "<<endl;
		cout <<"     jb@@@       g@@@@@@@  @@@@@@                  1@@@@@@                    "<<endl;
		cout <<"     @@@@         @@@@@@@@  g@@@@                  @@@@@@E                    "<<endl;
		cout <<"    g@@g!          @@@@@@@   @@@@g                 @@@@@@n                    "<<endl;
		cout <<"   !h@@@@@          @@@@@@   /ggmmg@@@             !@@@@@@                    "<<endl;
		cout <<"   @g@@@@g           @@@@@@gr g@@@@@@@@            @@@@@O@                    "<<endl;
		cout <<"   @g@@@@@b          g@O@@@@@@@@@@@@g@w           g@Og@@@@@                   "<<endl;
		cout <<"                     g@@@@@@@@g                  h@b@@@@@g@                   "<<endl;
		cout <<"                     m@@@@@@@@a                 vO@@@@g@@@@u                  "<<endl;
		cout <<"                       \b@´@a|                                                "<<endl;
	}
	else if (level == 2 && character == 2)
	{
		cout <<"When Stuart landed on that planet he saw the president's wife spaceship so he was sure"<< endl;
		cout <<"that was the right place. His previous knowledge about that place made him realise that the"<< endl;
		cout <<"safest place there was probably the basement of the church so that was his destination."<< endl;
		cout <<"When he got into the church he noticed the presence of some guards so he decided to use"<< endl;
		cout <<"his invisible clothes that he designed years before to get to the basement without anyone noticing. "<< endl;
        cout <<"'-What's that sound? Oh no, not you again, please don't make me use my fighting skills,"<< endl;
        cout <<"I'm not weak as my husband was.' - sayed the president's wife."<< endl;
		cout <<"'-This time I won't miss you, I will kill you.' - replied Stuart."<< endl;    
		cout<<"                    gtzg/                            "<<endl;
		cout<<"            1Tle - g- .-                             "<<endl;
		cout<<"          -  k;g` .ggx                               "<<endl;
		cout<<"          .gg.gg-gggTgg `                            "<<endl;
		cout<<"         ` 1p ,ggggggggF `@z|@`                      "<<endl;
		cout<<"            gggggmgg0emgd1.- gg `                    "<<endl;
		cout<<"         .gz:1. g@#g/!gx g+ .g                      "<<endl;
		cout<<"       -`gg  1gg0mg_g0gg@t``                         "<<endl;
		cout<<"          gg+g g@#gggmvw g:   .0@_                   "<<endl;
		cout<<"        . jesg  g@@gg-gigam  -0ggg!`                 "<<endl;
		cout<<"         - .- grgg=F@@-gg  . 1@bg                   "<<endl;
		cout<<"           -@gg@gh1c|!gg .    .!gn                   "<<endl;
		cout<<"          - ggg@gg0*fcngg -` ' cI -                  "<<endl;
		cout<<"         - -ulugggggneqggTn -bdm :                   "<<endl;
		cout<<"       -- -alT dg@@goff@ael1 gg:.                    "<<endl;
		cout<<"         `0ff ' ggggzsgg .yug@@ -                    "<<endl;
		cout<<"       --gyu`  @ggggstg . --@@' -                    "<<endl;
		cout<<"      - ggg`- ggz0gg|gg' '  . -`                     "<<endl;
		cout<<"        gg@  @p0ggxixgg . --    : :e.!! .            "<<endl;
		cout<<"      ._@g..egggggzh'mg    .- -.Fl!0!a'''--          "<<endl;
		cout<<"       gg- 'gggonjqqac@- .    ':ke|Iq-:'             "<<endl;
		cout<<"      @g#@ @ggggggfsx|og . --  ggg,                  "<<endl;
		cout<<"    -'i@  ggggg@ggghgggg'  .  @g-- ,                 "<<endl;
		cout<<"   `  -|#,@@egggggggggg@ . .-@g   ,                  "<<endl;
		cout<<"          @gg@@zgg@gggg-. .#q ..       +     -g*- .- "<<endl;
		cout<<"         @ggggg@T@ggglg  . @@@@       #g@gqgggU-     "<<endl;                     
		cout<<"         -u@@ggggcxlfg.  . '@b-  - 1gg@@wug@ggg@ -   "<<endl;
		cout<<"         @ghlgggg@Tygg '' .@00@.- kggg@lcgggggztFa.' "<<endl;
		cout<<"         @gg@fgggggggg-  ' @ggo0glggggslgggg@|uhgg@u "<<endl;
		cout<<"         @ggg@cgggggs. -- . @@gg@jggg@toggguupggg@gs "<<endl;
		cout<<"         -gg@g@tggggI -  . g0gggfegg@@kb@@@hggggggnb "<<endl;
		cout<<"          gggggbsggl@` .. ggggggTpg@g@ -- .- @@jueF0 "<<endl;
		cout<<"         -@@gggghIygg@-j 'ggg@ggnyp@  .     .-@@gg@@ "<<endl;
		cout<<"          @gg@gggg@gg@g@gggj@g@g@0@@@ '- -.g@@ggggg "<<endl;
		cout<<"           .@gggg@@ggfgggggghd@@@b@g@q@@0@@@gg@zggg@ "<<endl;
		cout<<"           .o@gggggggng@g@ggg@@@-@g@@g@@@qwgggggl|@  "<<endl;
		cout<<"            -wcg@ggggsggg|g@@@g - @@@0@@@@oyg@gg@0-` "<<endl;
		cout<<"              dI@gg@lggg@@@@     . .-@@@@@yt@@@@ `   "<<endl;
		cout<<"               goes|sI@gg@h' '                       "<<endl;
		cout<<"                @@@@@@@@@                            "<<endl;
	}
	else if (level == 2 && character == 3)
	{
		cout <<"After some days of traveling he finally arrived at the Gates of hell and there was"<< endl;
		cout <<"cerberu resting. Azreal screamed to wake him up."<< endl;
		cout <<"Azrael: 'WAKE UP! I'm here to take your powers cerberus!'"<< endl;
		cout <<"Cerberus:'Azrael? Long time no see' I heard you arent as powerful as you once were. Are"<< endl;
		cout <<"you sure you want to fight me?'"<< endl;
		cout <<"Azrael: ' I'm not as powerful as I were but I'm still better than you. Prepare yourself. Here I"<< endl;
		cout <<"come!'"<< endl;
		cout <<"                                                                              "<<endl;                                       
		cout <<"                        -@g                                                   "<<endl;
		cout <<"                  g    ,@U@                        :@                         "<<endl;
		cout <<"                  -O@   ggpg               @       ag#        pg@g@           "<<endl;
		cout <<"                   ggg@@@g#@b     g@      @gb      OUI@@@ggg@@@@@#@@          "<<endl;
		cout <<"                  g@gggg@@g@gg@   gO@    @@#w      @g@O@gg@g@@@@@@@@          "<<endl;
		cout <<"                @@@@@U@@g@@@@@@@n @O@@@q#O@gg      @@@m@@@@@@@@@@@g@          "<<endl;
		cout <<"                @ggg@@@ggggg@gg@@O@gg@g@@g@@g     g#gg@@@@@@@@@@@@p!          "<<endl;
		cout <<"              @mggggg@@@@gU@@@@@g@hg@@@g@@@@gh   ggOg@@@@@@@@@g!1@v@          "<<endl;
		cout <<"              O@@@@@g@@@@@@@@@@@ggo@@@@g@@@@@y@ @@@@gg@@@@@@az~@g@@@          "<<endl;
		cout <<"              g@@@@@@@@v1*E@@@@@g@g@@@@#@@@@@gg@oggggg@@@@@@@gq@@@g           "<<endl;
		cout <<"              @@´100qg=xiv@@@@@@O@@@@@@@@@@@@g@ggggg@@@@@@@g@@@=             "<<endl;
		cout <<"              ~@=+t !@p@g_@g@@@@@m@@@@@@wan@@@@g@@gg@@@@@@@@@@@~              "<<endl;
		cout <<"         O       /@!gI.ggg@g@@@@@@@ggTgEey!@@@@@@@@@@@@@@@@@@#`               "<<endl;
		cout <<"        g         @gg@@@@@@@@@@@@xg=_@. rOp:@@@g@@@@@@@@@@@-                 "<<endl;
		cout <<"       g          EU@@@@@@@@@@@@@@ifgZg@bgct#@#@@@@@@@@@@@@@                  "<<endl;
		cout <<"      g@           -gg@g@@@@@@@@@gk@@gqpgqhq@@@g@@@@@@@@@@@@                  "<<endl;
		cout <<"      U@             =@f#@@@@@@@@@m_@;ggaq@rg~@@@@@@@@@@@@@@                  "<<endl;
		cout <<"      g@            @|@g#@@@@@@@@g@g@znUdb,;@@@@@@g@@@@@@@@@                  "<<endl;
		cout <<"      g@g         -@@g@@n@@@@@@g@@b@;.ggeg@g@@@@@@FggOOm@g@d                  "<<endl;
		cout <<"       g@@       g@g@@j@@@@@@@@@@@g@g@@g@@@@@@@@@g@@@gg@@b@gr                 "<<endl;
		cout <<"       g@@@g   @cgh@@ggy@gm@gO#O#g@@@@g@@g@@@@@@@@@@@@@@@@-                   "<<endl;
		cout <<"        #@@g@@g@@@@gggg@g@O@@@@@@@@@@gg@@@@@@@vg*#@@@@@@@@                    "<<endl;
		cout <<"         @@pg@@@gmggggg@@@g@@@@@@@@@@#g@g@gggg@@@@@@@@@@@                     "<<endl;
		cout <<"         h@gggg@@O@ggggg@@@g@@@@@@@@@g@@g@gUUggg@@@@@@@g@                     "<<endl;
		cout <<"         F@g@g@@@@@@ggg@@@@@@@@@@@@@@U@@@@@@@@@@@@@@@@@@g                     "<<endl;
		cout <<"         @@@gg@@@m@@gg@@@@@@@@@@@@@@@g@@@@@@@@@@@@@@@g@gg@                    "<<endl;
		cout <<"        vO@ggg@@@q@gg@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@gg@i                   "<<endl;
		cout <<"        @g@@gg@@@k@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ggggm                   "<<endl;
		cout <<"        @@g@@@@@@u@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@g@@@@@@@@g                   "<<endl;
		cout <<"        @@@@@@@@g@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@g@@@@@@@@g@@                   "<<endl;
		cout <<"        @@g@@@@@m@@@@@@@@@g@@@@@@@@@@@@@@@@@@g@@g@@@@@@@@gg1                  "<<endl;
		cout <<"        @@@@@@@g@@@@@@@@@@@@@@@@@@g@@@@@@@@@@@@g@@@@@@@@@@@E                  "<<endl;
		cout <<"       g@@@@@@@@@@@@g@@@@@@@@@@@@g@@@@@@@@@@@@e zb@@@@@@@@@c                  "<<endl;
		cout <<"      b#@@@@gg @@g@@@@@@j  .@@@@@@@              @@@@@@@@@@                   "<<endl;
		cout <<"      @@@@@gg   @@@@@@@@@  @E@@@@@                @@@@@@@@gy                  "<<endl;
		cout <<"      g@@@g:    r@@@@@@@@  m@@@@@                  @@@@@@@I                   "<<endl;
		cout <<"     jb@@@       g@@@@@@@  @@@@@@                  1@@@@@@                    "<<endl;
		cout <<"     @@@@         @@@@@@@@  g@@@@                  @@@@@@E                    "<<endl;
		cout <<"    g@@g!          @@@@@@@   @@@@g                 @@@@@@n                    "<<endl;
		cout <<"   !h@@@@@          @@@@@@   /ggmmg@@@             !@@@@@@                    "<<endl;
		cout <<"   @g@@@@g           @@@@@@gr g@@@@@@@@            @@@@@O@                    "<<endl;
		cout <<"   @g@@@@@b          g@O@@@@@@@@@@@@g@w           g@Og@@@@@                   "<<endl;
		cout <<"                     g@@@@@@@@g                  h@b@@@@@g@                   "<<endl;
		cout <<"                     m@@@@@@@@a                 vO@@@@g@@@@u                  "<<endl;
		cout <<"                       \b@´@a|                   							  "<<endl;          
	}
	else if (level == 3 && character == 1)
	{
		cout <<"She walked in the gateway and all of a sudden she was in a cold desert and facing the God "<< endl;
		cout <<"Of War, Ares. Ares looked like a normal human at first glance. "<< endl;
		cout <<"Sheila' I heard what happened between you and the Ancient Guardian. I'm here to punish "<< endl;
		cout <<"you for that."<< endl;
		cout <<"Ares:' You? Insignificant. Ridiculous. Waste of time. I will finish you with one blow.'. After "<< endl;
		cout <<"Ares said this his skin turned into fire and flames. He dashed at an unseen speed to her and "<< endl;
		cout <<"the fight started."<< endl;
		cout<<"                                                 !                               "<<endl;
		cout<<"                                                @@                              "<<endl;
		cout<<"                                                @@                              "<<endl;
		cout<<"                                                @g                              "<<endl;
		cout<<"                                                @!                              "<<endl;
		cout<<"                                                @                               "<<endl;
		cout<<"                                                @                               "<<endl;
		cout<<"                                                +                               "<<endl;
		cout<<"                                               ~Or                              "<<endl;
		cout<<"                                             .jg#gg                             "<<endl;
		cout<<"                                             hg@gg##                            "<<endl;
		cout<<"                     g                       `g##p#g       f                    "<<endl;
		cout<<"                     @                       Egggg#g   -  -gg                   "<<endl;
		cout<<"                    gg@                      ggggagg   m- -gg                   "<<endl;
		cout<<"                  @@g|ggg               g  gg@gguggqgg- @__gg h@      g|        "<<endl;
		cout<<"                   Ogn@           -:do@gggg@gg@ubggggg@@ggu@@ggg   :gg#d        "<<endl;
		cout<<"                    gOO           OfzggU@g@g@g@ggg@ggggg@gm@g@g@m!`gggg`        "<<endl;
		cout<<"                    gg!         wOyOc#gg@@@gggg@gggq@@@@@g@@@@gggggggq          "<<endl;
		cout<<"                    ,g           ggOngg@g@g@gggggggOgggw@gg@ggggg#@@#           "<<endl;
		cout<<"                    !gj         hmgmOo@@@@g@gg#bg@ggmUbgggggggg@ggmg#g@E!jg@    "<<endl;
		cout<<"                    gg@/-Oo    g@gmggg@@gggg#gggggU#bO#ggUgggggggggmmug#ggg     "<<endl;
		cout<<"                    gg@@@@@@@@@egg@@g@@@@@@@@@@qg#oggmgggoUmggggg@gggOgggg      "<<endl;
		cout<<"                   @@@ggg@g@@@@@g@@@@@@@@@@@mggg@#g@ggg##gg#g@ggggggg@@ggT      "<<endl;
		cout<<"                   @@g@@@@g@@@g@g@@@@@n  @@@@mUggggggggggg#qTg@gggggg@gggmO     "<<endl;
		cout<<"                    !g@@@@@@@@g@g@@@     .g@@@@gg@@gu#ggggO#nEg@mgggag@ggg@     "<<endl;
		cout<<"               +i,._@agg@@@g@@@g@@       :@@@@@@@@@gggqggm=z!!gEg@g@gg@@g@      "<<endl;
		cout<<"                 gdqi!cg@:_giu          -@ggg@@gg@gg@geiFpq#mE!aU@g@@ggg      "<<endl;
		cout<<"              zggggOe:T+wgg@gg            dk@gggbggg@@gglTgbjgggrnbg@ggggg      "<<endl;
		cout<<"                ;vgE@y#E#g               ggg@gUj@@@@g@@@ggg@gggggg@@g@@@gdg     "<<endl;
		cout<<"                gmg@gjggg#dd             gg@g@@@@@@@m@xm@gg#ggg@@gmbgg@@@muk    "<<endl;
		cout<<"                  gggnggg                g@@@@@g@@@@@@ggggg#bqgg@gm@g@@g@x      "<<endl;
		cout<<"                  gggpg#@O              !@@@@gggg@g@gOggggsOOm#gggg@g@gg        "<<endl;
		cout<<"                  #@@mg@@g             @@@g@gggg@@@ggg@@ggaOhqggg@@@ggg         "<<endl;
		cout<<"                   @@gg@@             gggg@@@@@@gg@ggg@@@UdgO#ggg@g@ggg         "<<endl;
		cout<<"                   @@gg@@             -g@g@@g@@ggggggg@g@gggOggggggOg@g         "<<endl;
		cout<<"                 @@@@gggOgg            dg@@gg@@g@gg@ggg#g@gggg@gd@gggy_#        "<<endl;
		cout<<"                   @@gm@@              @U@@dggggggg@@@ggg@g@@g@@ggg@g---        "<<endl;
		cout<<"                   @@gF@@              ggggggg@@@g@@g@gggg@@@@@g@ggg@           "<<endl;
		cout<<"                   @@g1@@              m@@@@g@@@gg@@g@gggggg@@@gggg             "<<endl;
		cout<<"                   g@g!@@               g@gggggggmgggg@g@g@gggggg@g             "<<endl;
		cout<<"                   @g  g@               @@@ggg@gggg@@@@@gO@g@g@g                "<<endl;
		cout<<"                  okg  Ugo              @@@@@g@@gg@@@@@@@, gg@                  "<<endl;
		cout<<"                   gg  mg              i@@@@@g@gg@g@E@@@@g @gg                  "<<endl;
		cout<<"                   ogb gg             gggy@gOgg-@g@ggg@@q@g/@                   "<<endl;
		cout<<"                    g@ gg              @gOOUqb@   @@mT#OOga t                   "<<endl;
		cout<<"                    #g gg              g@g@ggg@    @gm@gggg                     "<<endl;
		cout<<"                   @##tggx            @@d@@g@mO    #gg@@gg@                     "<<endl;
		cout<<"                    gmOgg              @@@gjg@f    @@@gg@@                      "<<endl;
		cout<<"                    ggsUg              @@@gg@@     @@@g@g@                      "<<endl;
		cout<<"                    ggF#g              @@@gg@@     @@@@@g@                      "<<endl;
		cout<<"                    ggmgg              @@@gg@*      @@@@@@                      "<<endl;
		cout<<"                   OUggghm             q@@gg@       @@@@@@                      "<<endl;
		cout<<"                    ggUgg               @@@@g        @@@gg                      "<<endl;
		cout<<"                    Fggg#               @@g@~        @@ggm                      "<<endl;
		cout<<"                     ggg!              O@gg@         @@gg@                      "<<endl;
		cout<<"                     gUg               @gg#@g        @gmgg                      "<<endl;
		cout<<"                     gdg               gmggg         ggggg                      "<<endl;
		cout<<"                     dqU               gggg@         @ggggg                     "<<endl;
		cout<<"                      bh              @g@@gg1        @@ggggg                    "<<endl;
		
	}
	else if (level == 3 && character == 2)
	{
		cout <<"When he arrived, there was no one there, just forest. The family had killed all the habitats to"<< endl;
        cout <<"get an empty planet. He had to develop a machine with GPS to help him find the bunker."<< endl;
        cout <<"The bunker was near a river, in a beautiful valley. It was easy for him to enter the bunker and"<< endl;
        cout <<"find the boys room but there was a problem. The president's wife put a huge monster "<< endl;
        cout <<"guarding the kid but that won't be a problem."<< endl;
        cout <<"'-What are you doing? You shouldn't be here!' - exclaimed the monster."<< endl;
        cout <<"'- I'm here to kill the boy even if that means to also kill you.'.- Stuart replied."<< endl;
		cout<<"                                                 !                               "<<endl;
		cout<<"                                                @@                              "<<endl;
		cout<<"                                                @@                              "<<endl;
		cout<<"                                                @g                              "<<endl;
		cout<<"                                                @!                              "<<endl;
		cout<<"                                                @                               "<<endl;
		cout<<"                                                @                               "<<endl;
		cout<<"                                                +                               "<<endl;
		cout<<"                                               ~Or                              "<<endl;
		cout<<"                                             .jg#gg                             "<<endl;
		cout<<"                                             hg@gg##                            "<<endl;
		cout<<"                     g                       `g##p#g       f                    "<<endl;
		cout<<"                     @                       Egggg#g   -  -gg                   "<<endl;
		cout<<"                    gg@                      ggggagg   m- -gg                   "<<endl;
		cout<<"                  @@g|ggg               g  gg@gguggqgg- @__gg h@      g|        "<<endl;
		cout<<"                   Ogn@           -:do@gggg@gg@ubggggg@@ggu@@ggg   :gg#d        "<<endl;
		cout<<"                    gOO           OfzggU@g@g@g@ggg@ggggg@gm@g@g@m!`gggg`        "<<endl;
		cout<<"                    gg!         wOyOc#gg@@@gggg@gggq@@@@@g@@@@gggggggq          "<<endl;
		cout<<"                    ,g           ggOngg@g@g@gggggggOgggw@gg@ggggg#@@#           "<<endl;
		cout<<"                    !gj         hmgmOo@@@@g@gg#bg@ggmUbgggggggg@ggmg#g@E!jg@    "<<endl;
		cout<<"                    gg@/-Oo    g@gmggg@@gggg#gggggU#bO#ggUgggggggggmmug#ggg     "<<endl;
		cout<<"                    gg@@@@@@@@@egg@@g@@@@@@@@@@qg#oggmgggoUmggggg@gggOgggg      "<<endl;
		cout<<"                   @@@ggg@g@@@@@g@@@@@@@@@@@mggg@#g@ggg##gg#g@ggggggg@@ggT      "<<endl;
		cout<<"                   @@g@@@@g@@@g@g@@@@@n  @@@@mUggggggggggg#qTg@gggggg@gggmO     "<<endl;
		cout<<"                    !g@@@@@@@@g@g@@@     .g@@@@gg@@gu#ggggO#nEg@mgggag@ggg@     "<<endl;
		cout<<"               +i,._@agg@@@g@@@g@@       :@@@@@@@@@gggqggm=z!!gEg@g@gg@@g@      "<<endl;
		cout<<"                 gdqi!cg@:_giu          -@ggg@@gg@gg@geiFpq#mE!aU@g@@ggg      "<<endl;
		cout<<"              zggggOe:T+wgg@gg            dk@gggbggg@@gglTgbjgggrnbg@ggggg      "<<endl;
		cout<<"                ;vgE@y#E#g               ggg@gUj@@@@g@@@ggg@gggggg@@g@@@gdg     "<<endl;
		cout<<"                gmg@gjggg#dd             gg@g@@@@@@@m@xm@gg#ggg@@gmbgg@@@muk    "<<endl;
		cout<<"                  gggnggg                g@@@@@g@@@@@@ggggg#bqgg@gm@g@@g@x      "<<endl;
		cout<<"                  gggpg#@O              !@@@@gggg@g@gOggggsOOm#gggg@g@gg        "<<endl;
		cout<<"                  #@@mg@@g             @@@g@gggg@@@ggg@@ggaOhqggg@@@ggg         "<<endl;
		cout<<"                   @@gg@@             gggg@@@@@@gg@ggg@@@UdgO#ggg@g@ggg         "<<endl;
		cout<<"                   @@gg@@             -g@g@@g@@ggggggg@g@gggOggggggOg@g         "<<endl;
		cout<<"                 @@@@gggOgg            dg@@gg@@g@gg@ggg#g@gggg@gd@gggy_#        "<<endl;
		cout<<"                   @@gm@@              @U@@dggggggg@@@ggg@g@@g@@ggg@g---        "<<endl;
		cout<<"                   @@gF@@              ggggggg@@@g@@g@gggg@@@@@g@ggg@           "<<endl;
		cout<<"                   @@g1@@              m@@@@g@@@gg@@g@gggggg@@@gggg             "<<endl;
		cout<<"                   g@g!@@               g@gggggggmgggg@g@g@gggggg@g             "<<endl;
		cout<<"                   @g  g@               @@@ggg@gggg@@@@@gO@g@g@g                "<<endl;
		cout<<"                  okg  Ugo              @@@@@g@@gg@@@@@@@, gg@                  "<<endl;
		cout<<"                   gg  mg              i@@@@@g@gg@g@E@@@@g @gg                  "<<endl;
		cout<<"                   ogb gg             gggy@gOgg-@g@ggg@@q@g/@                   "<<endl;
		cout<<"                    g@ gg              @gOOUqb@   @@mT#OOga t                   "<<endl;
		cout<<"                    #g gg              g@g@ggg@    @gm@gggg                     "<<endl;
		cout<<"                   @##tggx            @@d@@g@mO    #gg@@gg@                     "<<endl;
		cout<<"                    gmOgg              @@@gjg@f    @@@gg@@                      "<<endl;
		cout<<"                    ggsUg              @@@gg@@     @@@g@g@                      "<<endl;
		cout<<"                    ggF#g              @@@gg@@     @@@@@g@                      "<<endl;
		cout<<"                    ggmgg              @@@gg@*      @@@@@@                      "<<endl;
		cout<<"                   OUggghm             q@@gg@       @@@@@@                      "<<endl;
		cout<<"                    ggUgg               @@@@g        @@@gg                      "<<endl;
		cout<<"                    Fggg#               @@g@~        @@ggm                      "<<endl;
		cout<<"                     ggg!              O@gg@         @@gg@                      "<<endl;
		cout<<"                     gUg               @gg#@g        @gmgg                      "<<endl;
		cout<<"                     gdg               gmggg         ggggg                      "<<endl;
		cout<<"                     dqU               gggg@         @ggggg                     "<<endl;
		cout<<"                      bh              @g@@gg1        @@ggggg                    "<<endl;
		
	}
	else if (level == 3 && character == 3)
	{
		cout <<"Some days passed by and all of a sudden Ares appeared. 'Azeal I can't believe you  "<< endl;
		cout <<"killed him. You are going to pay for this' said Ares while crying. 'Ares you just a little stone in  "<< endl;
		cout <<"my way to get to my father.' replied Azrael. 'How can you be so bloodthirst? We are family' "<< endl;
		cout <<"I'm done talking your going to pay'"<< endl;
		cout <<"The two gods colieded and started fighting..."<< endl;
		cout<<"                                                 !                               "<<endl;
		cout<<"                                                @@                              "<<endl;
		cout<<"                                                @@                              "<<endl;
		cout<<"                                                @g                              "<<endl;
		cout<<"                                                @!                              "<<endl;
		cout<<"                                                @                               "<<endl;
		cout<<"                                                @                               "<<endl;
		cout<<"                                                +                               "<<endl;
		cout<<"                                               ~Or                              "<<endl;
		cout<<"                                             .jg#gg                             "<<endl;
		cout<<"                                             hg@gg##                            "<<endl;
		cout<<"                     g                       `g##p#g       f                    "<<endl;
		cout<<"                     @                       Egggg#g   -  -gg                   "<<endl;
		cout<<"                    gg@                      ggggagg   m- -gg                   "<<endl;
		cout<<"                  @@g|ggg               g  gg@gguggqgg- @__gg h@      g|        "<<endl;
		cout<<"                   Ogn@           -:do@gggg@gg@ubggggg@@ggu@@ggg   :gg#d        "<<endl;
		cout<<"                    gOO           OfzggU@g@g@g@ggg@ggggg@gm@g@g@m!`gggg`        "<<endl;
		cout<<"                    gg!         wOyOc#gg@@@gggg@gggq@@@@@g@@@@gggggggq          "<<endl;
		cout<<"                    ,g           ggOngg@g@g@gggggggOgggw@gg@ggggg#@@#           "<<endl;
		cout<<"                    !gj         hmgmOo@@@@g@gg#bg@ggmUbgggggggg@ggmg#g@E!jg@    "<<endl;
		cout<<"                    gg@/-Oo    g@gmggg@@gggg#gggggU#bO#ggUgggggggggmmug#ggg     "<<endl;
		cout<<"                    gg@@@@@@@@@egg@@g@@@@@@@@@@qg#oggmgggoUmggggg@gggOgggg      "<<endl;
		cout<<"                   @@@ggg@g@@@@@g@@@@@@@@@@@mggg@#g@ggg##gg#g@ggggggg@@ggT      "<<endl;
		cout<<"                   @@g@@@@g@@@g@g@@@@@n  @@@@mUggggggggggg#qTg@gggggg@gggmO     "<<endl;
		cout<<"                    !g@@@@@@@@g@g@@@     .g@@@@gg@@gu#ggggO#nEg@mgggag@ggg@     "<<endl;
		cout<<"               +i,._@agg@@@g@@@g@@       :@@@@@@@@@gggqggm=z!!gEg@g@gg@@g@      "<<endl;
		cout<<"                 gdqi!cg@:_giu          -@ggg@@gg@gg@geiFpq#mE!aU@g@@ggg      "<<endl;
		cout<<"              zggggOe:T+wgg@gg            dk@gggbggg@@gglTgbjgggrnbg@ggggg      "<<endl;
		cout<<"                ;vgE@y#E#g               ggg@gUj@@@@g@@@ggg@gggggg@@g@@@gdg     "<<endl;
		cout<<"                gmg@gjggg#dd             gg@g@@@@@@@m@xm@gg#ggg@@gmbgg@@@muk    "<<endl;
		cout<<"                  gggnggg                g@@@@@g@@@@@@ggggg#bqgg@gm@g@@g@x      "<<endl;
		cout<<"                  gggpg#@O              !@@@@gggg@g@gOggggsOOm#gggg@g@gg        "<<endl;
		cout<<"                  #@@mg@@g             @@@g@gggg@@@ggg@@ggaOhqggg@@@ggg         "<<endl;
		cout<<"                   @@gg@@             gggg@@@@@@gg@ggg@@@UdgO#ggg@g@ggg         "<<endl;
		cout<<"                   @@gg@@             -g@g@@g@@ggggggg@g@gggOggggggOg@g         "<<endl;
		cout<<"                 @@@@gggOgg            dg@@gg@@g@gg@ggg#g@gggg@gd@gggy_#        "<<endl;
		cout<<"                   @@gm@@              @U@@dggggggg@@@ggg@g@@g@@ggg@g---        "<<endl;
		cout<<"                   @@gF@@              ggggggg@@@g@@g@gggg@@@@@g@ggg@           "<<endl;
		cout<<"                   @@g1@@              m@@@@g@@@gg@@g@gggggg@@@gggg             "<<endl;
		cout<<"                   g@g!@@               g@gggggggmgggg@g@g@gggggg@g             "<<endl;
		cout<<"                   @g  g@               @@@ggg@gggg@@@@@gO@g@g@g                "<<endl;
		cout<<"                  okg  Ugo              @@@@@g@@gg@@@@@@@, gg@                  "<<endl;
		cout<<"                   gg  mg              i@@@@@g@gg@g@E@@@@g @gg                  "<<endl;
		cout<<"                   ogb gg             gggy@gOgg-@g@ggg@@q@g/@                   "<<endl;
		cout<<"                    g@ gg              @gOOUqb@   @@mT#OOga t                   "<<endl;
		cout<<"                    #g gg              g@g@ggg@    @gm@gggg                     "<<endl;
		cout<<"                   @##tggx            @@d@@g@mO    #gg@@gg@                     "<<endl;
		cout<<"                    gmOgg              @@@gjg@f    @@@gg@@                      "<<endl;
		cout<<"                    ggsUg              @@@gg@@     @@@g@g@                      "<<endl;
		cout<<"                    ggF#g              @@@gg@@     @@@@@g@                      "<<endl;
		cout<<"                    ggmgg              @@@gg@*      @@@@@@                      "<<endl;
		cout<<"                   OUggghm             q@@gg@       @@@@@@                      "<<endl;
		cout<<"                    ggUgg               @@@@g        @@@gg                      "<<endl;
		cout<<"                    Fggg#               @@g@~        @@ggm                      "<<endl;
		cout<<"                     ggg!              O@gg@         @@gg@                      "<<endl;
		cout<<"                     gUg               @gg#@g        @gmgg                      "<<endl;
		cout<<"                     gdg               gmggg         ggggg                      "<<endl;
		cout<<"                     dqU               gggg@         @ggggg                     "<<endl;
		cout<<"                      bh              @g@@gg1        @@ggggg                    "<<endl;
		
	}
}




		
	
